#input central values



In [4]:
from pandas import read_csv
from numpy import set_printoptions
from sklearn import preprocessing
from sklearn.impute import SimpleImputer
import pandas as pd

#loading data into the dataframe
header_name = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
my_data = read_csv('venv/pima_indians_diabetes_2.csv', names= header_name)

print(my_data.shape)

#getting the rows with empty values from the actual dataframe
empty_values = my_data[my_data.isna().any(axis = 1)]
print(empty_values)
print('----- empty rows of the diabetic data------')




(771, 9)
     preg   plas  pres  skin  test  mass   pedi   age  class
440     2  120.0   NaN    26  16.0  36.8  0.766  22.0      0
661     2  120.0  58.0    26  16.0   NaN  0.766  22.0      0
770     2    NaN  58.0    26   NaN  28.4  0.766   NaN      0


replacing them with the central value - it could be better to separate the independent variable from the dependent variables

In [9]:
#better still use pandas to get the first 8 columns  as the independent data
print("The extracted independent data")
indepent_variable = my_data[my_data.columns[0:8]]
print(indepent_variable.shape)
print(indepent_variable.tail(5))
print("-------first the last 5 rows of extracted independent data-----")

The extracted independent data
(771, 8)
     preg   plas  pres  skin   test  mass   pedi   age
766     2  122.0  70.0    27    0.0  36.8  0.340  27.0
767     5  121.0  72.0    23  112.0  26.2  0.245  30.0
768     1  126.0  60.0     0    0.0  30.1  0.349  47.0
769     1   93.0  70.0    31    0.0  30.4  0.315  23.0
770     2    NaN  58.0    26    NaN  28.4  0.766   NaN
-------first the last 5 rows of extracted independent data


In [12]:
#get the row with empty value in the extracted dataframe
print("Empty rows of the extracted independent data")
empty_independet = indepent_variable[indepent_variable.isna().any(axis = 1)]
print(empty_independet)
print(indepent_variable.shape)
print("-------empty rows of extracted independent data ------\n")

Empty rows of the extracted independent data
     preg   plas  pres  skin  test  mass   pedi   age
440     2  120.0   NaN    26  16.0  36.8  0.766  22.0
661     2  120.0  58.0    26  16.0   NaN  0.766  22.0
770     2    NaN  58.0    26   NaN  28.4  0.766   NaN
(771, 8)
-------empty rows of extracted independent data ------



SIMPLEIMPUTER TO REPLACE NULL OR MISSING VALUES

In [21]:
#use the simple imputer function to replace the null values with median
#imputer = SimpleImputer(strategy='median')#replace most_frequent with mean, median and observe
#imputer.fit(indepent_variable)
#imputer.transform(empty_independet)

#use the simple imputer function to replace the null values with mean
imputer = SimpleImputer(strategy='mean')#replace most_frequent with mean, median and observe
imputer.fit(my_data)
new_data = imputer.transform(my_data)
new_data = pd.DataFrame(new_data)

print(indepent_variable.tail(5))
new_data = pd.DataFrame(new_data)
print(new_data.tail(5))

     preg   plas  pres  skin   test  mass   pedi   age
766     2  122.0  70.0    27    0.0  36.8  0.340  27.0
767     5  121.0  72.0    23  112.0  26.2  0.245  30.0
768     1  126.0  60.0     0    0.0  30.1  0.349  47.0
769     1   93.0  70.0    31    0.0  30.4  0.315  23.0
770     2    NaN  58.0    26    NaN  28.4  0.766   NaN
       0           1     2     3           4     5      6          7    8
766  2.0  122.000000  70.0  27.0    0.000000  36.8  0.340  27.000000  0.0
767  5.0  121.000000  72.0  23.0  112.000000  26.2  0.245  30.000000  0.0
768  1.0  126.000000  60.0   0.0    0.000000  30.1  0.349  47.000000  1.0
769  1.0   93.000000  70.0  31.0    0.000000  30.4  0.315  23.000000  0.0
770  2.0  120.892208  58.0  26.0   79.633766  28.4  0.766  33.211688  0.0


    FEATURE SCALING

In [2]:
# scaling using the MinMaxscaler
from pandas import read_csv
from numpy import set_printoptions
from sklearn import preprocessing
from sklearn.impute import SimpleImputer
import pandas as pd

#loading data into the dataframe
header_name = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
my_data = read_csv('venv/pima_indians_diabetes_2.csv', names= header_name)

print(my_data.shape)

#getting the rows with empty values from the actual dataframe
empty_values = my_data[my_data.isna().any(axis = 1)]
print(empty_values)
print('----- empty rows of the diabetic data------')
imputer = SimpleImputer(strategy='mean')#replace most_frequent with mean, median and observe
imputer.fit(my_data)
new_data = imputer.transform(my_data)
new_data = pd.DataFrame(new_data)


new_data = pd.DataFrame(new_data)
print(new_data.tail(5))

scale_data_array = preprocessing.MinMaxScaler(feature_range=(0,1))
rescaler_data_array = scale_data_array.fit_transform(new_data)

set_printoptions(precision=1)
print("\n Scaled data:\n", rescaler_data_array[0:10])

(771, 9)
     preg   plas  pres  skin  test  mass   pedi   age  class
440     2  120.0   NaN    26  16.0  36.8  0.766  22.0      0
661     2  120.0  58.0    26  16.0   NaN  0.766  22.0      0
770     2    NaN  58.0    26   NaN  28.4  0.766   NaN      0
----- empty rows of the diabetic data------
       0           1     2     3           4     5      6          7    8
766  2.0  122.000000  70.0  27.0    0.000000  36.8  0.340  27.000000  0.0
767  5.0  121.000000  72.0  23.0  112.000000  26.2  0.245  30.000000  0.0
768  1.0  126.000000  60.0   0.0    0.000000  30.1  0.349  47.000000  1.0
769  1.0   93.000000  70.0  31.0    0.000000  30.4  0.315  23.000000  0.0
770  2.0  120.892208  58.0  26.0   79.633766  28.4  0.766  33.211688  0.0

 Scaled data:
 [[0.4 0.7 0.6 0.4 0.  0.5 0.2 0.5 1. ]
 [0.1 0.4 0.5 0.3 0.  0.4 0.1 0.2 0. ]
 [0.5 0.9 0.5 0.  0.  0.3 0.3 0.2 1. ]
 [0.1 0.4 0.5 0.2 0.1 0.4 0.  0.  0. ]
 [0.  0.7 0.3 0.4 0.2 0.6 0.9 0.2 1. ]
 [0.3 0.6 0.6 0.  0.  0.4 0.1 0.2 0. ]
 [0.2 0.4

    L1 Normalisation

In [3]:
#Normalisation L1
from pandas import read_csv
from numpy import set_printoptions
from sklearn import preprocessing
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import Normalizer

#loading data into the dataframe
header_name = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
my_data = read_csv('venv/pima_indians_diabetes_2.csv', names= header_name)

print(my_data.shape)

#getting the rows with empty values from the actual dataframe
empty_values = my_data[my_data.isna().any(axis = 1)]
print(empty_values)
print('----- empty rows of the diabetic data------')
imputer = SimpleImputer(strategy='mean')#replace most_frequent with mean, median and observe
imputer.fit(my_data)
new_data = imputer.transform(my_data)
new_data = pd.DataFrame(new_data)


new_data = pd.DataFrame(new_data)
print(new_data.tail(5))

my_data_normalizer  = Normalizer(norm='l1').fit(new_data)
my_normalized_data = my_data_normalizer.transform(new_data)

set_printoptions(precision=2)
print("\n My normalized data; \n", my_normalized_data [0:3])

(771, 9)
     preg   plas  pres  skin  test  mass   pedi   age  class
440     2  120.0   NaN    26  16.0  36.8  0.766  22.0      0
661     2  120.0  58.0    26  16.0   NaN  0.766  22.0      0
770     2    NaN  58.0    26   NaN  28.4  0.766   NaN      0
----- empty rows of the diabetic data------
       0           1     2     3           4     5      6          7    8
766  2.0  122.000000  70.0  27.0    0.000000  36.8  0.340  27.000000  0.0
767  5.0  121.000000  72.0  23.0  112.000000  26.2  0.245  30.000000  0.0
768  1.0  126.000000  60.0   0.0    0.000000  30.1  0.349  47.000000  1.0
769  1.0   93.000000  70.0  31.0    0.000000  30.4  0.315  23.000000  0.0
770  2.0  120.892208  58.0  26.0   79.633766  28.4  0.766  33.211688  0.0

 My normalized data; 
 [[0.02 0.43 0.21 0.1  0.   0.1  0.   0.14 0.  ]
 [0.   0.36 0.28 0.12 0.   0.11 0.   0.13 0.  ]
 [0.03 0.59 0.21 0.   0.   0.07 0.   0.1  0.  ]]


    L2 Normalization

In [4]:
#Normalisation L1
from pandas import read_csv
from numpy import set_printoptions
from sklearn import preprocessing
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import Normalizer

#loading data into the dataframe
header_name = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
my_data = read_csv('venv/pima_indians_diabetes_2.csv', names= header_name)

print(my_data.shape)

#getting the rows with empty values from the actual dataframe
empty_values = my_data[my_data.isna().any(axis = 1)]
print(empty_values)
print('----- empty rows of the diabetic data------')
imputer = SimpleImputer(strategy='mean')#replace most_frequent with mean, median and observe
imputer.fit(my_data)
new_data = imputer.transform(my_data)
new_data = pd.DataFrame(new_data)


new_data = pd.DataFrame(new_data)
print(new_data.tail(5))

my_data_normalizer  = Normalizer(norm='l2').fit(new_data)
my_normalized_data = my_data_normalizer.transform(new_data)

set_printoptions(precision=2)
print("\n My normalized data; \n", my_normalized_data [766:770])

(771, 9)
     preg   plas  pres  skin  test  mass   pedi   age  class
440     2  120.0   NaN    26  16.0  36.8  0.766  22.0      0
661     2  120.0  58.0    26  16.0   NaN  0.766  22.0      0
770     2    NaN  58.0    26   NaN  28.4  0.766   NaN      0
----- empty rows of the diabetic data------
       0           1     2     3           4     5      6          7    8
766  2.0  122.000000  70.0  27.0    0.000000  36.8  0.340  27.000000  0.0
767  5.0  121.000000  72.0  23.0  112.000000  26.2  0.245  30.000000  0.0
768  1.0  126.000000  60.0   0.0    0.000000  30.1  0.349  47.000000  1.0
769  1.0   93.000000  70.0  31.0    0.000000  30.4  0.315  23.000000  0.0
770  2.0  120.892208  58.0  26.0   79.633766  28.4  0.766  33.211688  0.0

 My normalized data; 
 [[0.01 0.81 0.47 0.18 0.   0.24 0.   0.18 0.  ]
 [0.03 0.65 0.39 0.12 0.6  0.14 0.   0.16 0.  ]
 [0.01 0.84 0.4  0.   0.   0.2  0.   0.31 0.01]
 [0.01 0.74 0.55 0.25 0.   0.24 0.   0.18 0.  ]]


    Binarization

In [7]:
#Binarization
from pandas import read_csv
from numpy import set_printoptions
from sklearn import preprocessing
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import Binarizer

#loading data into the dataframe
header_name = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
my_data = read_csv('venv/pima_indians_diabetes_2.csv', names= header_name)

print(my_data.shape)

#getting the rows with empty values from the actual dataframe
empty_values = my_data[my_data.isna().any(axis = 1)]
print(empty_values)
print('----- empty rows of the diabetic data------')
imputer = SimpleImputer(strategy='mean')#replace most_frequent with mean, median and observe
imputer.fit(my_data)
new_data = imputer.transform(my_data)
new_data = pd.DataFrame(new_data)


new_data = pd.DataFrame(new_data)
print(new_data.tail(5))

data_array = new_data.values


binarized_data = Binarizer(threshold=0.5).fit(data_array)
Data_binarized = binarized_data.transform(data_array)

set_printoptions(precision=2)
print("\n My binarized data: ", Data_binarized [766:770])

(771, 9)
     preg   plas  pres  skin  test  mass   pedi   age  class
440     2  120.0   NaN    26  16.0  36.8  0.766  22.0      0
661     2  120.0  58.0    26  16.0   NaN  0.766  22.0      0
770     2    NaN  58.0    26   NaN  28.4  0.766   NaN      0
----- empty rows of the diabetic data------
       0           1     2     3           4     5      6          7    8
766  2.0  122.000000  70.0  27.0    0.000000  36.8  0.340  27.000000  0.0
767  5.0  121.000000  72.0  23.0  112.000000  26.2  0.245  30.000000  0.0
768  1.0  126.000000  60.0   0.0    0.000000  30.1  0.349  47.000000  1.0
769  1.0   93.000000  70.0  31.0    0.000000  30.4  0.315  23.000000  0.0
770  2.0  120.892208  58.0  26.0   79.633766  28.4  0.766  33.211688  0.0

 My binarized data:  [[1. 1. 1. 1. 0. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 1. 0. 1. 0.]
 [1. 1. 1. 0. 0. 1. 0. 1. 1.]
 [1. 1. 1. 1. 0. 1. 0. 1. 0.]]


    Standardisation

In [9]:
#Standardisation
from pandas import read_csv
from numpy import set_printoptions
from sklearn import preprocessing
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

#loading data into the dataframe
header_name = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
my_data = read_csv('venv/pima_indians_diabetes_2.csv', names= header_name)

print(my_data.shape)

#getting the rows with empty values from the actual dataframe
empty_values = my_data[my_data.isna().any(axis = 1)]
print(empty_values)
print('----- empty rows of the diabetic data------')
imputer = SimpleImputer(strategy='mean')#replace most_frequent with mean, median and observe
imputer.fit(my_data)
new_data = imputer.transform(my_data)
new_data = pd.DataFrame(new_data)


new_data = pd.DataFrame(new_data)
print(new_data.tail(5))

data_array = new_data.values

data_scaler = StandardScaler().fit(data_array)
data_rescaled = data_scaler.transform(data_array)

set_printoptions(precision=2)
print("\n My Standard rescaled  data: ", data_rescaled [765:770])

(771, 9)
     preg   plas  pres  skin  test  mass   pedi   age  class
440     2  120.0   NaN    26  16.0  36.8  0.766  22.0      0
661     2  120.0  58.0    26  16.0   NaN  0.766  22.0      0
770     2    NaN  58.0    26   NaN  28.4  0.766   NaN      0
----- empty rows of the diabetic data------
       0           1     2     3           4     5      6          7    8
766  2.0  122.000000  70.0  27.0    0.000000  36.8  0.340  27.000000  0.0
767  5.0  121.000000  72.0  23.0  112.000000  26.2  0.245  30.000000  0.0
768  1.0  126.000000  60.0   0.0    0.000000  30.1  0.349  47.000000  1.0
769  1.0   93.000000  70.0  31.0    0.000000  30.4  0.315  23.000000  0.0
770  2.0  120.892208  58.0  26.0   79.633766  28.4  0.766  33.211688  0.0

 My Standard rescaled  data:  [[ 1.83 -0.62  0.36  1.72  0.87  0.12 -0.91  2.54 -0.73]
 [-0.55  0.03  0.05  0.4  -0.69  0.61 -0.4  -0.53 -0.73]
 [ 0.35  0.    0.15  0.15  0.28 -0.74 -0.69 -0.27 -0.73]
 [-0.84  0.16 -0.47 -1.29 -0.69 -0.24 -0.37  1.17  1.37]
